name: "[MAIN] Build and Release"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release?'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: [1.24]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libvulkan-dev libxkbcommon-x11-dev libx11-xcb-dev libegl1-mesa-dev libwayland-dev libx11-dev libxcursor-dev libxfixes-dev pkg-config

      - name: Install Go dependencies
        run: go mod tidy

      - name: Build Go project
        run: |
          GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || 'windows' }} GOARCH=amd64 go build -o network-interaction-${{ matrix.os }}-${{ matrix.go-version }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: network-interaction-${{ matrix.os }}-${{ matrix.go-version }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            network-interaction-windows-1.20
            network-interaction-linux-1.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
